### ISSUE TITLE
关于重建OSA的一些想法

### ISSUE THREAD

**Issue by H2Sxxa** [CCZU-DEV/osa-init#1]
通过 `README.md` ，我对当年成立OSA的背景大致了解了，我自己也是十分倡导开源精神的，可现在很可惜的是在CCZU没有见到前辈们的后人，我现在是120的成员，当前120也面临着转型，我个人想要重拾OSA，我知道这很难，尽管可能没有人气，但可以普及开源精神到一部分人，这也是很好的。

~~终于找到组织了，快让我加入~~

我不知道我的这个Issue前辈们能否收到，也不知道我这个Issue是否是挖坟，如果能够抽空回复的话，我将会十分感激。

~~所有观点仅代表个人观点~~

**Comment by oziasly** [comment]
好好好，你们可以搞点小项目哇

**Comment by stdrc** [comment]
Hi 不好意思我刚看到这个 issue，没想到 OSA 还能有人传承（其实当初还真的想到过这种可能性，CCZU 的情况大概就是每隔几年会一些人有动力组织一些新的尝试）

我已经把你拉到了这个 org，如果你想的话可以在这个 org 建 repo，logo 和社团名你都可以复用，祝你成功！

**Comment by H2Sxxa** [comment]
> Hi 不好意思我刚看到这个 issue，没想到 OSA 还能有人传承（其实当初还真的想到过这种可能性，CCZU 的情况大概就是每隔几年会一些人有动力组织一些新的尝试）
> 
> 我已经把你拉到了这个 org，如果你想的话可以在这个 org 建 repo，logo 和社团名你都可以复用，祝你成功！

感谢前辈的回复，其实我原本是打算在Gh建一个新的组织，找几个认识的人，把能fork继续维护的都fork一下，稍微完善后，明年再从新生里找找有没有稍微了解开源社区/开发这块的 ~~（其实已经着手做了一部分了，为了区分还在OSA中加了个S）~~ ，不知道前辈会不会介意。

**Comment by stdrc** [comment]
> > Hi 不好意思我刚看到这个 issue，没想到 OSA 还能有人传承（其实当初还真的想到过这种可能性，CCZU 的情况大概就是每隔几年会一些人有动力组织一些新的尝试）
> 
> > 
> 
> > 我已经把你拉到了这个 org，如果你想的话可以在这个 org 建 repo，logo 和社团名你都可以复用，祝你成功！
> 
> 
> 
> 感谢前辈的回复，其实我原本是打算在Gh建一个新的组织，找几个认识的人，把能fork继续维护的都fork一下，稍微完善后，明年再从新生里找找有没有稍微了解开源社区/开发这块的 ~~（其实已经着手做了一部分了，为了区分还在OSA中加了个S）~~ ，不知道前辈会不会介意。

完全没问题！重要的是促进交流、推广开源、提高技术水平，具体操作怎么来都行

**Comment by H2Sxxa** [comment]
再一次感谢前辈！

**Comment by Cml1230** [comment]
我感觉现在的常大,哎,一言难进.

**Comment by Cml1230** [comment]
现在的常大,哎,一言难尽

**Comment by H2Sxxa** [comment]
> 现在的常大,哎,一言难尽

尽力试试吧，也许不一定有结果，但能改变一点，也就够了
